version: '2'
services:
  web1:
    build: .
    ports: 
      - "3000"
  web2:
    build: .
    ports: 
      - "3000"
  web3:
    build: .
    ports: 
      - "3000"
  ngnix:
    build: ./nginx
    links: 
      - web1:web1
      - web2:web2
      - web3:web3
    ports:
      - 80:80
      - 443:443
